name: human_tracking
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - opencv
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - cudatoolkit=11.3  # Remove this line if using CPU only
  - pip
  - pip:
    - mediapipe
    - onnxruntime-gpu  # Change to onnxruntime for CPU only
    - ultralytics  # for YOLOv8
    - fastapi
    - uvicorn
    - cython
    - lap  # for Linear Assignment Problem solver
    - pytest  # for testing
    # ByteTrack will be installed from Git 